-- 003_system_metrics.sql

ALTER TABLE servers ADD COLUMN cpu_pct FLOAT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN mem_used_bytes BIGINT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN mem_total_bytes BIGINT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN disk_used_bytes BIGINT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN disk_total_bytes BIGINT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN load_1min FLOAT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN load_5min FLOAT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN load_15min FLOAT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN uptime_seconds BIGINT DEFAULT NULL;
ALTER TABLE servers ADD COLUMN cpu_count INT DEFAULT NULL;
